name: Check latest release dependencies

on:
  schedule:
    - cron:  "31 5 * * *" # this is utc time

jobs:
  release-dependency-scan:
    name: Owasp Release Dependency Scanning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Store latest actions
        run: |
          cp -R .github .github_latest
      - name: Checkout latest release
        run: |
          git fetch --all --tags --prune
          export LATEST_TAG=$(git tag | sed '/-/d' | sort -t "." -k1,1 -k2,2n -k3,3n | tail -1)
          export OWASP_UPDATES_BRANCH=$(git ls-remote --heads origin ${LATEST_TAG}_owasp_updates)
          if [[ -z ${OWASP_UPDATES_BRANCH} ]]; then git checkout "tags/${LATEST_TAG}" -b latest_release; else git checkout "${LATEST_TAG}_owasp_updates"; fi
      - name: Cache Gradle cache and wrapper
        uses: actions/cache@v2
        with:
          path: |
            gradle_home/caches
            gradle_home/wrapper
          key: ${{ runner.os }}-owasp-release-dependency-scan-with-gradle-${{ hashFiles('app/build.gradle') }}
      - name: OWASP dependency check
        uses: ./.github_latest/docker-owasp-dependency-check-android
        env:
          GRADLE_HOME: "./gradle_home"
      - uses: actions/upload-artifact@v2
        if: ${{ success() || failure() }}
        with:
          name: dependency-check-result
          path: |
            ./build/reports/dependency-check-report.html
            ./app/build/reports/dependency-check-report.html
      - name: Notify to slack
        if: ${{ failure() }}
        uses: ./.github_latest/docker-slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          text: "OWASP dependency check - release"
          status: ${{job.status}}
